#pragma once

#define IDR_SMAA_EDGES_VS       101
#define IDR_SMAA_WEIGHTS_VS     102
#define IDR_SMAA_NEIGHBORHOOD_VS 103
#define IDR_SMAA_EDGES_PS       104
#define IDR_SMAA_WEIGHTS_PS     105
#define IDR_SMAA_NEIGHBORHOOD_PS 106
